version: '3.8'

services:
  mysqld_exporter:
    image: prom/mysqld-exporter:v0.12.1
    container_name: mysqld_exporter
    environment:
      MYSQLD_EXPORTER_USER: "prometheus"
      MYSQLD_EXPORTER_PASS: "root123456"
      DATA_SOURCE_NAME: "prometheus:root123456@tcp(39.107.235.125:3306)/"
    command:
      - "--config.my-cnf="  
    ports:
      - "9104:9104"
    depends_on:
      - prometheus

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - "9100:9100"
    depends_on:
      - prometheus    

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis_exporter
    environment:
      REDIS_ADDR: "redis://39.107.235.125:6379"
      REDIS_PASSWORD: "cdz2024" 
    ports:
      - "9121:9121"
    depends_on:
      - prometheus    

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus  